### ISSUE TITLE
pytest-dev 2.0.2 release

### ISSUE THREAD

**Issue by monkey-debugger** [pytest-dev/pytest-timeout#114]
@flub Do you need anything else to release #111? Jetbrains broke the PyCharm debugger detection again by releasing 2021.3. This change would fix that as well.

If there's still work to be done for a 2.0.2 release I can take a look at it and see if I have time to work on it.

Thx for maintaining this repository :smiley:!

**Comment by flub** [comment]
done

**Comment by flub** [comment]
btw, thanks for prompting.  i'd have never remembered to release it otherwise :)
