### ISSUE TITLE
Confusing sentence in README

### ISSUE THREAD

**Issue by pkoch** [pytest-dev/pytest-timeout#124]
> This is not the timeout you are looking for!

Is this a joke/reference that I didn't get (like maybe [Star Wars](https://youtu.be/532j-186xEQ?t=25)?), or is there something in particular that makes it unsuitable for most people? If so, what should I be on the lookout for?

It's been great using it so far! Thank you for open-sourcing it! 🤗

**Comment by flub** [comment]
On Mon 14 Mar 2022 at 13:22 -0700, Paulo Köch wrote:

>> This is not the timeout you are looking for!
>
> Is this a joke/reference that I didn't get (like maybe [Star Wars](https://youtu.be/532j-186xEQ?t=25)?), or is there something in particular that makes it unsuitable for most people? If so, what should I be on the lookout for?

It is an attempt to make people carefully read the README and consider
whether the restrictions and limitations match what's needed for their
expectations.  Specifically many people have been trying to use this
plugin for "this bit of code is starting to take too long", which is
very unreliable in a testing environment and not what this plugin was
meant to address - a lot of design decisions would and should have been
different if it was meant to address this.

I don't think this was meant as a star wars reference.  Maybe that is a
bit confusing :(

> It's been great using it so far! Thank you for open-sourcing it! 🤗

great to hear!  and thanks!

**Comment by pkoch** [comment]
Is there perhaps a way we could have an intro that makes those trade-off more obvious?

When I started using this plugin, I've gone through the README, saw nothing particularly jarring, and just started using the plugin! I did do in fear, since I didn't understand why such a strong warning was given at the top of the README, and I was sure that I wasn't understanding the source of concerns (other than "scheduling things is hard, especially so when doing it cross-platform, and we don't use any real-time mechanisms", which I was sure wouldn't warrant such a prominent warning).

What's the tl;dr that you'd want your users to know? Have you maybe had previous reports of unexpected behavior, or feeling like the features offered by the plugin are a bit too lackluster?

**Comment by flub** [comment]
On Tue 14 Jun 2022 at 11:11 -0700, Paulo Köch wrote:

> Is there perhaps a way we could have an intro that makes those trade-off more obvious?

I'd be open to a PR that uses more neutral language, sure.  I may have
written this in a bit of frustration a long time ago.

> What's the tl;dr that you'd want your users to know?

I think this from earlier in this thread describes this:

> Specifically many people have been trying to use this
> plugin for "this bit of code is starting to take too long", which is
> very unreliable in a testing environment and not what this plugin was
> meant to address - a lot of design decisions would and should have been
> different if it was meant to address this.

Instead the purpose of the plugin is "this is test is taking sooo long
that things have gone very wrong by now and we'll probably be better off
if it fails now".

**Comment by pkoch** [comment]
Added a [PR](https://github.com/pytest-dev/pytest-timeout/pull/135). Can you check if that's what you're expecting? Do you want me to make some tweaks?

**Comment by pkoch** [comment]
PR got in. Closing!
