### ISSUE TITLE
gracefully exit the program

### ISSUE THREAD

**Issue by wzhy920127** [pytest-dev/pytest-timeout#138]
https://github.com/pytest-dev/pytest-timeout/blob/7d4c413a6344edd8340628354419a324e68c6cb7/pytest_timeout.py#L440
Why not use `sys.exit()` to exit the program?
 It can exit normally without affecting subsequent cases.

**Comment by flub** [comment]
The aim is to give as much guarantee as possible that the process will terminate.  A plain `sys.exit()` does allow too many ways for the process to still not exit.
