### ISSUE TITLE
Pytest-timeout is not activated in debugging mode

### ISSUE THREAD

**Issue by CharlesGaydon** [pytest-dev/pytest-timeout#139]
this may be a feature and not a bug. 
In VS Code, I usually run pytest from my debugging config. after some confusing waits, I read that [this was expected](https://github.com/pytest-dev/pytest-timeout#debugger-detection).
Is there any way to still time out my test even in debugging mode ?
Thanks :)

**Comment by flub** [comment]
I guess it is not.  I probably would accept a PR that adds something like `--always-timeout` or `--disable-debugger-detection` or something like that.

**Comment by michaeljpeters** [comment]
See https://github.com/pytest-dev/pytest-timeout/pull/143
