### ISSUE TITLE
New Version

### ISSUE THREAD

**Issue by aqeelat** [pytest-dev/pytest-timeout#147]
Hi @flub 

Would you be able to release a new version? It's been a while since the last release.

**Comment by flub** [comment]
Why not. Could you check the currently supported python versions and make
PRs updating CI to use the right CPython and PyPy versions to see if there
are any issues?

I'm on holiday currently though, so it'll take a week or two before I'm
back with a computer.  But you can already prepare things in PRs and if CI
looks good I can sporadically merge them.

Cheers

**Comment by aqeelat** [comment]
@flub now that we fixed the ci issues. Can you please release the new version?

**Comment by flub** [comment]
@aqeelat thanks for the ping and helping get things along.  I've released a new version.

I realise this is rather untimely, every time I need to do some pytest-timeout work I always end up having to re-discover how to do a bunch of things as I don't do them often enough.  Which makes it more of a chore to do and means I need more time for it.  I've in the past tried to look for someone to take over pytest-timeout maintenance but that wasn't successful.  So I hope this sporadic maintenance is not too bad, at least pytest-timeout is pretty stable but please do not hesitate to make clear how urgent releases are for folks to be unblocked etc.

Thanks!

**Comment by aqeelat** [comment]
@flub I'd be happy to help.

**Comment by flub** [comment]
On Sun 08 Oct 2023 at 08:28 -0700, Abdullah Alaqeel wrote:

> @flub I'd be happy to help.

would be great!  getting the CI to be happy on all platforms again would
be nice.  I noticed not all of them are successful anymore.

**Comment by aqeelat** [comment]
@flub I think the issue is a flaky test because as you can see, https://github.com/pytest-dev/pytest-timeout/actions/runs/6446997087 and https://github.com/pytest-dev/pytest-timeout/actions/runs/6446998530 are building the same commit but one is passing and the other one is failing. I don't currently have a windows machine to investigate but I'll try to find out what's going on.

Other things I would love to do:
1. add a release github action so that we can automatically release from github
2. replace the pre-commits with ruff

**Comment by flub** [comment]
@aqeelat Could you move these 3 to separate issues to track/discuss?

But a quick reply already:

1. i'd definitely love this
2. sounds fine, but would be good to loop in the person who added pre-commit in the first place

**Comment by aqeelat** [comment]
@flub can you please give me access to push to this repo? I have been added as a contributor but I cannot create new branches and push to them.

**Comment by flub** [comment]
You can currently create PRs though, isn't that sufficient for now?  What would this unblock?
