### ISSUE TITLE
New hook called right before timeout occurs

### ISSUE THREAD

**Issue by pytest-timeout-bot** [pytest-dev/pytest-timeout#15]
**[Original report](https://bitbucket.org/pytest-dev/pytest-timeout/issue/15) by Bruno Oliveira (Bitbucket: [nicoddemus](https://bitbucket.org/nicoddemus), GitHub: [nicoddemus](https://github.com/nicoddemus)).**

----------------------------------------

It would be nice if `pytest-timeout` supplied a hook that is called right before a timeout occurs:

```python
def pytest_about_to_timeout(config):
    """Called when a timeout is reached and the test suite is about to be aborted.
    """
```

It could be called as the first thing in `dump_stacks`. 

What do you think @flub? If you like the idea I could work on a PR.

**Comment by graingert** [comment]
@nicoddemus in your gui application you probably want a 16ms timeout on callbacks from the eventloop, rather than a big global one for the whole test

**Comment by nicoddemus** [comment]
@graingert what do you mean, posting a 16ms callback to the eventloop and terminate the test if the callback is triggered?

**Comment by chrahunt** [comment]
Another concrete use case: I have a library that requires multiprocess interaction. The tests spawn subprocesses and bugs often result in the processes hanging, leading to a timeout. It has been really helpful to get the stacks of all the child processes for later inspection, especially for issues that only show up in CI. Example usage [here](https://github.com/chrahunt/quicken/blob/2dd00a5f024d7b114b211aad8a2618ec8f101956/tests/conftest.py#L92).

**Comment by flub** [comment]
Closing as no one seems to be working on this.  Feel free to open a PR however.
