### ISSUE TITLE
pytest timeout in pytest.ini is not working

### ISSUE THREAD

**Issue by jiz17043** [pytest-dev/pytest-timeout#156]
![image](https://github.com/pytest-dev/pytest-timeout/assets/44070470/3b1a3117-085d-413a-96fd-302102eae28a)
I have added the timeout in the pytest.ini and installed pytest-timeout. But the test still is working after 5 seconds. And it also has a warning for not recognizing the timeout 
![image](https://github.com/pytest-dev/pytest-timeout/assets/44070470/5049b44a-30b3-41f0-8f22-efa96a683e6b)

**Comment by jiz17043** [comment]
pytest-benchmark      4.0.0
pytest-cov            4.1.0
pytest-json           0.4.0
pytest-mock           3.11.1
pytest-timeout        2.2.0
pytest-xdist          3.3.1
python-apt            2.2.1
python-dateutil       2.8.2

![image](https://github.com/pytest-dev/pytest-timeout/assets/44070470/fddedb8c-dcc5-48e6-b295-1da3a5c8a5cc)

**Comment by jiz17043** [comment]
It seems that it is not in my global python environment

**Comment by The-Compiler** [comment]
Closing this then, given that the plugin wasn't installed in the first place.
