### ISSUE TITLE
[QUESTION] When can we expect a release?

### ISSUE THREAD

**Issue by s0undt3ch** [pytest-dev/pytest-timeout#167]
Sorry for bringing this up in an issue, but, following the merge of https://github.com/pytest-dev/pytest-timeout/pull/162, I have a [PR](https://github.com/saltstack/salt/pull/65902) on one of my projects waiting on a release of pytest-timeout.

When can we expect a release?
Is there anything I can do to help expedite the release?

**Comment by flub** [comment]
Hi, fair enough to ask.  Maybe once #165 is merged?  Hopefully that should not be too  many days off now.

**Comment by s0undt3ch** [comment]
@flub Awesome! Thank You.

**Comment by flub** [comment]
Never take my word on a deadline it seems :see_no_evil: 

let me know if i somehow messed up this release though
