### ISSUE TITLE
cut a new release on PyPI

### ISSUE THREAD

**Issue by marcelotrevisani** [pytest-dev/pytest-timeout#51]
Hi,

Just a very minor thing, the home page url on [PyPi](https://pypi.org/project/pytest-timeout/) is pointing to the old repo. It would be nice to update that too  :)

It is currently pointing to http://bitbucket.org/pytest-dev/pytest-timeout/

**Comment by flub** [comment]
Oh, thanks for the reminder!  I think we need a new release for this.

**Comment by graingert** [comment]
I'd like a release soon for https://github.com/pytest-dev/pytest-timeout/pull/42

@flub the people that can make a release are: anatoly, flub, hpk, nicoddemus, pfctdayelise, ronny and The_Compiler

**Comment by flub** [comment]
thanks for you patience, a new release is tagged and on pypi
