### ISSUE TITLE
[Docs] document additional configuration methods

### ISSUE THREAD

**Issue by asfaltboy** [pytest-dev/pytest-timeout#57]
In particular, I was missing the new `func_only` option as added by @s0undt3ch in 1.3.1

**Comment by flub** [comment]
Could you make a PR with this?

**Comment by flub** [comment]
`func_only` is mentioned in the readme by now

**Comment by asfaltboy** [comment]
Sorry @flub I missed your reply ... and after years, sadly Github notifications are still difficult 😅 

Had a look at the new README , well done it looks awesome 🥇 👍

**Comment by flub** [comment]
On Sun 08 Oct 2023 at 06:45 -0700, Pavel Savchenko wrote:

> Sorry @flub I missed your reply ... and after years, sadly Github notifications are still difficult 😅 

github notifications are the worst, totally agreed

> Had a look at the new README , well done it looks awesome 🥇 👍 

probably wasn't me but some other contributor :)
