### ISSUE TITLE
Is timeout-method help text misleading?

### ISSUE THREAD

**Issue by nakulka2** [pytest-dev/pytest-timeout#61]
py.test --help after installing pytest-timeout (version 1.3.3) shows: "Timeout mechanism to use. 'signal' uses SIGALRM if available, 'thread' uses a timer thread. The default is to use 'signal' and fall back to 'thread'." for --timeout-method.

Is this sentence specifically misleading: "The default is to use 'signal' and fall back to 'thread'."?

Looking at the code on line: https://github.com/pytest-dev/pytest-timeout/blob/master/pytest_timeout.py#L158, I feel it is either using sigalarm or thread. I do not see where it is trying to do sigalarm first and then if sigalarm does not work, fall back on thread.

I have a sample test (I unfortunately can not give a minimal repro instructions here) which can not get killed by sigalarm but does get killed by thread. However it gets killed by thread only if I explicitly chose thread as the timeout method. Also, I have checked that my platform does support sigalarm.

Thanks!

**Comment by flub** [comment]
Yeah, maybe.  What it is trying to say is that if you do not configure a timeout method, there is a **global** default.  If your system supports SIGALRM then it uses the "signal" method, otherwise it uses the "thread" method.  The code for this is here: https://github.com/pytest-dev/pytest-timeout/blob/aafe48740344aec3ee246876db37ffea208ac929/pytest_timeout.py#L21-L25  At the start of a test the method is looked up, if this was not configured at all for this test the global default ends up being used.  Once the timeout expires it can no longer change the method.

Do you have a suggestion to improve this text?

**Comment by nakulka2** [comment]
Thanks for clearing the confusion. The "fallback" part of the help text is actually very appealing. In my case specifically I hoped that we use the small hammer (signal) and if that does not work then pull out the big hammer (thread).

I know you said that

> Once the timeout expires it can no longer change the method."

However I would still hope that this can be considered as a feature request. Signal specifically is pretty good for two reasons: 1. Test run still continues after the test that times out. 2. I get a junit report after the test run. So I would hope that all tests that can be killed by signal be given that chance before using a much more forceful method like timer thread.

> Do you have a suggestion to improve this text?

How about instead of [this](https://github.com/pytest-dev/pytest-timeout/blob/master/pytest_timeout.py#L30-L34), we have:
```
METHOD_DESC = """
Timeout mechanism to use.  'signal' uses SIGALRM. 'thread' uses a timer
thread. If user does not explicitly provide a timeout method, 'signal' is used
by default used on platforms that support SIGALRM and 'thread' is default on
other platforms.
""".strip()
````

Of course I would hope that original help text can stay and we actually take in my feature request :)

**Comment by flub** [comment]
> I know you said that
> 
> > Once the timeout expires it can no longer change the method."
> 
> However I would still hope that this can be considered as a feature request.

I'll be honest and say this is very unlikely, unless someone else implements this in a reasonably elegant way.  I'm afraid that after all these years I'm personally still of the opinion these kind of use cases are doing the wrong thing.  But I've accepted that many users don't see it that way, so I've started accepting PRs that add features towards this.  So if you're motivated and have a reasonable design go for it.  :)

> > Do you have a suggestion to improve this text?
> 
> How about instead of [this](https://github.com/pytest-dev/pytest-timeout/blob/master/pytest_timeout.py#L30-L34), we have:
> 
> ```
> METHOD_DESC = """
> Timeout mechanism to use.  'signal' uses SIGALRM. 'thread' uses a timer
> thread. If user does not explicitly provide a timeout method, 'signal' is used
> by default used on platforms that support SIGALRM and 'thread' is default on
> other platforms.
> """.strip()
> ```

Sounds good!  Could you do a PR with this?

**Comment by nakulka2** [comment]
Thanks for taking in my request!

Tbh, I do not know the process of doing a PR. If there is a doc, I will definitely consider in future. I still use pytest-timeout and I am sure I will have more questions/ feature requests in future too.
