### ISSUE TITLE
CLI threshold for each test

### ISSUE THREAD

**Issue by danilito19** [pytest-dev/pytest-timeout#75]
Currently the only way to fail/terminate a test that takes longer than Xsecs is to decorate the test with `@pytest.mark.timeout(X)`. However, if I don't want to decorate every single test I have, but I still want pytest to tell me a test was too long, a CLI argument could work here.

Using the existing CLI `--timeout=X` isn't sufficient because that thresholds the entire test suite, instead of a single test.

**Comment by flub** [comment]
Not sure I follow.  You both say you want to change the timeout for all
tests but that --timeout doesn't work because it affects all tests.

If you're debugging a particular issue select just the tests you care
about and use --timeout.  If not, use a high global timeout.  There
should only be rare exceptions where you'd need to use the decorator to
tweak this.

**Comment by danilito19** [comment]
> There should only be rare exceptions where you'd need to use the decorator to tweak this.

I think we have a different use-case in mind then. I'd like to use `--timeout` in my CI as a step to warn me if I or another dev wrote a test that's too long. So it's not a one time thing, debug, and remove the decorator, it's a flag that could stay used as a warning.

**Comment by flub** [comment]
Apologies, I still don't follow.  What is wrong with using `--timeout=30` on CI?  That way all tests will be stopped if they take more than 30s.  For integration tests perhaps the value should be a few minutes.  But generally you should be able to pick a limit which is high enough to catch only problematic cases.

**Comment by danilito19** [comment]
@flub apologies. I think the documentation misled me on the use case for the flag.

> Now you can run tests using a timeout, in seconds, after which they will be terminated:

> pytest --timeout=300

"after which they will be terminated" isn't really telling me what will happen. It sounds like the entire test suite will be terminated? Each test?

**Comment by flub** [comment]
On Wed 16 Sep 2020 at 05:37 -0700, danilito19 wrote:

> @flub apologies. I think the documentation misled me on the use case for the flag.
>
>> Now you can run tests using a timeout, in seconds, after which they will be terminated:
>
>> pytest --timeout=300
>
> "after which they will be terminated" isn't really telling me what will happen. It sounds like the entire test suite will be terminated? Each test?

In fact both could happen, this depends on the timeout method selected.
This is again described in the README.

I agree the text you quote could be rather confusing at the point where
it is written - that is without having read the entire README.  Would
something like this improve things?

```

Now you can run the test suite while setting a timeout in seconds, any
individual test which takes longer than the given duration will be
terminated.

    pytest --timeout=300


Furthermore you can use a decorator to set the timeout for an
individual test.  If combined with the `--timeout` flag this will
override the timeout for this individual test:

```

I'm cautions to add too much text that early though.  It seems the
README often already contains too much info for people to digest ;)  But
that doesn't mean we can't try to improve it's readabilty.

What do you think?  Do you have an alternative proposal to improve this?

**Comment by danilito19** [comment]
Yes I think that ABSOLUTELY makes the functionality much more clear and adds very little wording. Go for it!
