### ISSUE TITLE
Test timeout when using pycharm debug console

### ISSUE THREAD

**Issue by adamgoldfeld** [pytest-dev/pytest-timeout#78]
I've experienced the following behavior:
1.In pycharm, set a breakpoint in a test with timeout marking.
2.Debug with pytest.
3.After entering debug mode, evaluate an expression in the debug console.
4.Timeout triggers, the debug console stays active but you can no longer debug the code.

Is this an expected behavior?
If not is there a solution?

Thanks in advance,
Adam.

**Comment by flub** [comment]
Basically don't invoke the test with a timeout when you want to jump into a debugger.
But #62 tried to provide a more automatic work-around for this as is briefly mentioned in the readme at https://github.com/pytest-dev/pytest-timeout#debugger-detection as well.  If that doesn't work and you think it should perhaps you can look into why it doesn't detect your debugger and provide a patch?

**Comment by yanqd0** [comment]
This helps me when debug in vscode or PyCharm:

```sh
pytest -p no:timeout ...
```

But there will be a `PytestUnknownMarkWarning`.

It is recommended to implement a `--no-timeout` argument to disable self when it is normally open. Some other plugin has this feature, like [pytest-cov] and [pytest-pylint].

[pytest-cov]:https://github.com/pytest-dev/pytest-cov
[pytest-pylint]:https://github.com/carsongee/pytest-pylint

**Comment by thedrow** [comment]
```python
import os
if "PYDEVD_LOAD_VALUES_ASYNC" in os.environ:
  disable_timeouts()
```

Should automatically do the trick. `PYDEVD_LOAD_VALUES_ASYNC` is only present when PyDevD is running.
