### ISSUE TITLE
Allow different timer signals to be used

### ISSUE THREAD

**Issue by rowleya** [pytest-dev/pytest-timeout#79]
Python supports a number of different timer signals; currently pytest-timeout uses signal.ITIMER_REAL (see https://github.com/pytest-dev/pytest-timeout/blob/master/pytest_timeout.py#L203-L208), but it is more useful on a busy system to use ITIMER_VIRTUAL or ITIMER_PROF (see https://docs.python.org/3/library/signal.html?highlight=signal#signal.ITIMER_REAL).  It would be useful if this could become an option.

**Comment by flub** [comment]
On Wed 13 Jan 2021 at 01:02 -0800, Andrew Rowley wrote:

> Python supports a number of different timer signals; currently
> pytest-timeout uses signal.ITIMER_REAL (see
> https://github.com/pytest-dev/pytest-timeout/blob/master/pytest_timeout.py#L203-L208),
> but it is more useful on a busy system to use ITIMER_VIRTUAL or
> ITIMER_PROF (see
> https://docs.python.org/3/library/signal.html?highlight=signal#signal.ITIMER_REAL).
> It would be useful if this could become an option.

What do you mean "it is more useful on a busy system"?  What are the
tradeoffs to be made here?

**Comment by rowleya** [comment]
ITIMER_VIRTUAL and ITIMER_PROF only count down the time when the task is actually running on the CPU, whereas ITIMER_REAL counts down on a wall clock.  On a system where there are lots of processes running (for example, a testing server), this means that the runs might be inconsistent; one might time out just because time had passed but it hadn't actually had much time with the CPU.  If the timer type were a command line option (leaving ITIMER_REAL as the default for backwards compatibility), it would allow the user to choose what the timeout really means.

**Comment by flub** [comment]
Hmm, this sounds like another variation of the disagreement I have with
a lot of users: timeouts are inherently flaky, therefore the only
timeout which makes sense is a huge-way-to-large timeout which you'd
never reasonably trigger so that it only does something when things have
properly gone wrong, for example tests are entirely deadlocked.  If the
timeout is huge anyway, why still care about resolution?

But I've been persuaded by users before to trade off features for
simplicity.  So perhaps there's more to your busy test servers and
spurious timeouts you get from them.  How do you use pytest-timeout?
And/or how do you want to use it?

**Comment by rowleya** [comment]
OK, well if something has gone wrong, I don't want the test to run forever.  If I have to set an impossibly large timeout, like in terms of hours, I might as well not set one at all.  So our current timeout is 20 minutes for any test, which is way beyond any reasonable run, in general, but short enough for the tests to actually stop.  Most of the time this is fine, but sometimes the server ends up running more tests than usual (like lots of people happen to commit at the same time), and then 20 minutes of wall-clock time is not reasonable.  Using CPU time would mean that we wouldn't have to worry about how many tests are run at the same time; it would be consistent over any runs that you could throw at it.

To be clear, this isn't about resolution of the timer.  It is about when the timer counts.  The default timer ticks with the clock on the wall, but the other options exist to tick only when the thread is being serviced.  I would prefer to make use of these options to ensure consistency of tests regardless of environment.

**Comment by flub** [comment]
Hi, sorry for the delay.

Ok, 20 minutes certainly seems like a long enough timeout, I certainly
don't find your expectation unreasonable here.  For completeness, what
is the "fast" execution time of this test when running on a
non-congested box?  Only a few minutes?

But yes, hour-long timeouts are not useful.  I'm surprised your machines
are under that heavy load, but sure.  I guess this seems reasonable to
adopt.  Do you think it would need to be configurable or is it possible
to always depend on the clock?  Could you propose changes in a PR?

Cheers,
Floris

**Comment by rowleya** [comment]
The "fast" execution time is usually maybe a few minutes.

PR in #81 as requested.  I have made it configurable as I guess different tests might want different behaviours depending on what they do.  The tests show that you can't use "sleep" for example here, as sleep normally doesn't actually execute anything in the thread, so the timeout never happens during a sleep when using these different timers.

**Comment by flub** [comment]
closing as matching PR is closed
