### ISSUE TITLE
Using timeout as a pass criteria, not fail.

### ISSUE THREAD

**Issue by tfurf** [pytest-dev/pytest-timeout#82]
I have a top-level test (near main) that starts up a long-running (indefinite) process, and I want to check that indeed the process runs for a while without crashing. Can `pytest-timeout` be used for this use case, maybe somehow with `pytest-xfail`? 

Ideally such a test 'passes' if the timeout is reached, but, fails if any other error occurs beforehand.

**Comment by flub** [comment]
I don't think pytest-timeout is useful for this.
