### ISSUE TITLE
Timeout takes into account session scope fixture

### ISSUE THREAD

**Issue by keu** [pytest-dev/pytest-timeout#96]
Even though the timeout is set for individual test it seems that actual execution time of global fixtures (session scope) affect this.

**Comment by keu** [comment]
```python
@pytest.fixture(autouse=True, scope="session")
def my_startup():
    sleep(11)


@pytest.mark.timeout(10)
class TestSomething:
    def test1(self):
        sleep(8)

**Comment by flub** [comment]
Yes, this is kind of a side-effect of how things are organised in pytest.  Fixtures are part of the normal test and get lazily created.  This is also how pytest reports errors on creation of fixtures for example.

A while ago someone added the `timeout_func_only` config option and the `func_only` marker if you do now want to time out your fixtures.  In general I think you shouldn't have timeouts so short that this is an issue though, but there is the option.

**Comment by keu** [comment]
@flub Thanks for the response. In real project fixtures could load many heavy things (like docker pull image, etc) so when I check that test took no more than N seconds I mean the test itself, not preparations. I will try the config option and let you know if it works.
